mazekatonic:
  resource: "@MarvinMazekatonicBundle/Controller/"
  type:     annotation
  prefix:   /


mazekatonic_rest:
  resource : "@MarvinMazekatonicBundle/Resources/config/routing_rest.yml"
  type: rest
  prefix:   /api